# Generated by Django 5.1.1 on 2024-09-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelinfo",
            name="detailIntro",
            field=models.TextField(default="", verbose_name="详情介绍"),
        ),
    ]
